[green_agent]
agentbeats_id = "019bba35-9cbc-7950-a8da-41c06010d6bf"
env = { LLM_API_KEY = "${LLM_API_KEY}", DATASET="/app/data/public.csv", YOUR_NAME="ai noobs", EMAIL_ADDRESS="ai.noobs.2025@gmail.com", LOCAL_LLM_MODEL_PATH="/app/tools/models/llama-3.2-1b-instruct-q4_k_m.gguf" }

[[participants]]
agentbeats_id = "019bba61-5125-7dc2-97ab-ed46f4acbd9d"
name = "finance-purple-agent"
env = {}

[config]
# Add your assessment config here
method = "run_assessment"
args = { 
    num_tasks = 1,
    white_address = "http://finance-purple-agent:9009"  # <-- point to the purple agent container
